### ISSUE TITLE
Cookie error

### ISSUE THREAD

**Issue by pablodz** [mkhorasani/Streamlit-Authenticator#113]
when I press F5 on latest version and I already logged in this error appears

```python

2024-01-24 21:28:24.423 Uncaught app exception
Traceback (most recent call last):
  File "/root/.local/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/app/pages/📚VozygoLogs.py", line 577, in <module>
    authenticator.login()
  File "/root/.local/lib/python3.11/site-packages/streamlit_authenticator/authenticate.py", line 246, in login
    self._check_cookie()
  File "/root/.local/lib/python3.11/site-packages/streamlit_authenticator/authenticate.py", line 128, in _check_cookie
    st.session_state['name'] = self.credentials['usernames'][self._get_username('id', self.token['id'])]['name']
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: False
````

**Comment by mkhorasani** [comment]
Dear @pablodz, please make sure to save changes to the config file after every widget as shown below:

```
with open('../config.yaml', 'w') as file:
    yaml.dump(config, file, default_flow_style=False)
```

This is to ensure that the new 'ID' field that is being automatically generated will be saved to the config file.

**Comment by mkhorasani** [comment]
Dear @pablodz, I have decided to axe Streamlit-Authenticator v0.2.5 and instead replace it with v0.3.0 to resolve this issue. Please download this latest version.

**Comment by pablodz** [comment]
Ok, thank you
