### ISSUE TITLE
streamlit_authenticator import error

### ISSUE THREAD

**Issue by adonventure** [mkhorasani/Streamlit-Authenticator#155]
2024-04-21 00:06:05.545 Uncaught app exception
Traceback (most recent call last):
  File "/home/talat/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/home/talat/seoart/streamlit_authenticator_test.py", line 4, in <module>
    import streamlit_authenticator as stauth
  File "/home/talat/.local/lib/python3.10/site-packages/streamlit_authenticator/__init__.py", line 15, in <module>
    from .authenticate import Authenticate
  File "/home/talat/.local/lib/python3.10/site-packages/streamlit_authenticator/authenticate/__init__.py", line 19, in <module>
    from .cookie import CookieHandler
  File "/home/talat/.local/lib/python3.10/site-packages/streamlit_authenticator/authenticate/cookie/__init__.py", line 13, in <module>
    from jwt import DecodeError, InvalidSignatureError
ImportError: cannot import name 'DecodeError' from 'jwt' (/home/talat/.local/lib/python3.10/site-packages/jwt/__init__.py)

**Comment by mkhorasani** [comment]
Dear @adonventure, I believe you may have downloaded an incorrect distribution of the PyJWT. I recommend you create a new clean environment and reinstall streamlit-authenticator and please make sure that you have `PyJWT >=2.3.0` installed.

**Comment by adonventure** [comment]
Assalamu Alaikum and JAZAKALLAH KHAIR
