### ISSUE TITLE
multipage multiuser app authenticator object

### ISSUE THREAD

**Issue by AH012** [mkhorasani/Streamlit-Authenticator#218]
Hey ! hope you are doing well and thank you for this amazing project.

I am getting a little problem using the authenticator object. Can you help me please ?

Here is my code in my home.py file

```
authenticator = stauth.Authenticate(
    credentials=config['credentials'],
    cookie_name=config['cookie']['name'],
    cookie_key=config['cookie']['key'],
    cookie_expiry_days=config['cookie']['expiry_days'],
    auto_hash=False,
    pre_authorized=None
)

if "authenticator" not in st.session_state:
    st.session_state.authenticator = authenticator

authenticator.login()
```

As you said in your README, in my pages/page1.py file, I implemented this code

```
from ..home import authenticator

if "authenticator" not in st.session_state:
    st.session_state.authenticator = authenticator

st.session_state["authenticator"].login(location="unrendered")
```

When I hard refresh the page1, I am getting this error 

```
Traceback (most recent call last):
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/cogic_dashboard/pages/avoir.py", line 29, in <module>
    st.session_state["authenticator"].login(location="unrendered")
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit_authenticator/views/authentication_view.py", line 274, in login
    if not st.session_state['authentication_status']:
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit/runtime/state/session_state_proxy.py", line 100, in __getitem__
    return get_session_state()[key]
           ~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit/runtime/state/safe_session_state.py", line 94, in __getitem__
    return self._state[key]
           ~~~~~~~~~~~^^^^^
  File "/Users/aminehammami/Documents/societe/cogic/cogic-dashboard/venv/lib/python3.11/site-packages/streamlit/runtime/state/session_state.py", line 457, in __getitem__
    raise KeyError(_missing_key_error_message(key))
KeyError: 'st.session_state has no key "authentication_status". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'
```

Besides, I am getting a little bit confused with authenticator object being instantiated only one time. I think it disables the multi user aspect of my app. For example: When the app is instantiated for the first time, it will store the cookie of the first user. The second user will then connect to my app, will get the credentials of my first user and will get his roles

Version used: 0.4.1

**Comment by mkhorasani** [comment]
Hi @AH012, first of all in v0.4.1 onwards the `pre_authorized` parameter has been removed from the `Authenticate` class and instead you can provide a list of pre-authorized users directly to the `register_user` widget. Please correct your code as follows:

home.py
```
import streamlit as st
import streamlit_authenticator as stauth 

import yaml
from yaml.loader import SafeLoader

with open('config.yaml') as file:
    config = yaml.load(file, Loader=SafeLoader)

authenticator = stauth.Authenticate(
    credentials=config['credentials'],
    cookie_name=config['cookie']['name'],
    cookie_key=config['cookie']['key'],
    cookie_expiry_days=config['cookie']['expiry_days'],
    auto_hash=False
    )

if "authenticator" not in st.session_state:
    st.session_state.authenticator = authenticator

authenticator.login()
```

page1.py
```
import streamlit as st

# if "authenticator" not in st.session_state:
#     st.session_state.authenticator = authenticator

st.session_state["authenticator"].login(location="unrendered")

if st.session_state['authentication_status']:
    st.write('hello')
```

**Comment by AH012** [comment]
Thank you for your answer !

This is the error I am getting when I hard refresh the page1.py 

KeyError: 'st.session_state has no key "authenticator". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'

**Comment by mkhorasani** [comment]
> Thank you for your answer !
> 
> This is the error I am getting when I hard refresh the page1.py
> 
> `KeyError: 'st.session_state has no key "authenticator". Did you forget to initialize it? More info: https://docs.streamlit.io/develop/concepts/architecture/session-state#initialization'`

Did you follow the above example that I sent you?

**Comment by AH012** [comment]
Yes Exactly the same
